name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # cache npm packages to speed up deployments
            - uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: 'npm'
                cache-dependency-path: |
                  package-lock.json
                  examples/typescript/package-lock.json

            - name: Install root dependencies
              run: npm ci

            - name: Build root project
              run: npm run build

            - name: Install TypeScript example dependencies
              run: |
                cd examples/typescript
                npm install

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}